#!/bin/sh

dest=$HOME/devel/dotfiles

cp /usr/share/xsessions/dwm.desktop $dest -f
cp $HOME/.bashrc $dest -f
cp $HOME/.config/.vimrc $dest -f
cp $HOME/.config/compton.conf $dest -f
# cp $HOME/.config/liferea/feedlist.opml $dest -f
cp /usr/bin/onstart $dest -f

