#!/bin/sh

dotfiles=$HOME/dev/dotfiles2.0

cp /usr/share/xsessions/dwm.desktop $dotfiles
cp $HOME/.bashrc $dotfiles
cp $HOME/.config/.vimrc $dotfiles
cp $HOME/.config/compton.conf $dotfiles
# cp $HOME/.config/liferea/feedlist.opml $dotfiles
cp /usr/bin/onstart $dotfiles
cp /usr/bin/onexit $dotfiles
cp $HOME/.config/nvim/init.vim $dotfiles
cp $HOME/.profile $dotfiles
cp /etc/profile $dotfiles
cp /etc/modprobe.d/droidcam.conf $dotfiles
cp -rf $HOME/.local/share/qutebrowser/userscripts $dotfiles
cp $HOME/.config/alacritty/alacritty.toml $dotfiles
