#!/bin/sh

xwallpaper --zoom ~/Pictures/wallpapers/current.png

compton --config ~/.config/compton.conf -b

dwm-bar loop &

setxkbmap -layout us,sk -variant ,qwerty -option 'grp:alt_caps_toggle'

xset r rate 280 40
